# Generated by Django 4.1.7 on 2023-08-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainboard_web',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정 일시'),
        ),
    ]
